name: 'analytics'
version: '1.0.0'
config-version: 2

# Project profile
profile: 'analytics'

# Model paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Model configurations
models:
  analytics:
    # Staging models - materialized as views
    staging:
      +materialized: view
      +schema: staging

    # Core business logic - materialized as tables
    marts:
      +materialized: table
      +schema: marts

      core:
        +tags: ["core", "daily"]

      finance:
        +tags: ["finance", "daily"]

      marketing:
        +tags: ["marketing", "hourly"]

# Seeds configuration
seeds:
  analytics:
    +schema: seeds

# Snapshots configuration
snapshots:
  analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Documentation
docs-paths: ["docs"]

# Variables
vars:
  start_date: '2024-01-01'
  currency: 'USD'
