version: 2

models:
  # Staging Models - Northwind
  - name: stg_orders
    description: "Cleaned and enriched Northwind orders with calculated shipping metrics"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
      - name: shipping_performance
        description: "Categorized shipping performance (On Time, Late, etc.)"
      - name: is_shipped
        description: "Boolean flag indicating if order has been shipped"

  - name: stg_order_details
    description: "Order line items with calculated pricing and discounts"
    columns:
      - name: order_id
        description: "Foreign key to orders"
        tests:
          - not_null
      - name: product_id
        description: "Foreign key to products"
        tests:
          - not_null
      - name: extended_price
        description: "Line item total after discounts"
        tests:
          - not_null
      - name: discount
        description: "Discount applied to this line item (0-1)"

  - name: stg_customers
    description: "Cleaned customer data with regional groupings"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: company_name
        description: "Customer company name"
        tests:
          - not_null
      - name: region_group
        description: "Geographic region grouping (North America, Europe, etc.)"
      - name: contact_type
        description: "Type of contact (Owner, Manager, Sales Rep, etc.)"

  - name: stg_products
    description: "Product catalog with inventory and pricing"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Product name"
        tests:
          - not_null
      - name: category_name
        description: "Product category"
      - name: stock_status
        description: "Current inventory status (Normal, Low Stock, Out of Stock, etc.)"
      - name: price_tier
        description: "Price category (Premium, Mid-Range, Economy)"

  # Mart Models - Analytics
  - name: fct_order_performance
    description: "Daily order performance metrics including shipping and revenue"
    columns:
      - name: date
        description: "Date of orders"
        tests:
          - unique
          - not_null
      - name: total_orders
        description: "Total number of orders placed"
      - name: total_revenue
        description: "Total revenue for the day"
      - name: shipping_rate_pct
        description: "Percentage of orders shipped"
      - name: on_time_rate_pct
        description: "Percentage of shipped orders delivered on time"
      - name: avg_order_value
        description: "Average revenue per order"

  - name: dim_customer_metrics
    description: "Customer dimension with lifetime metrics and RFM segmentation"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: lifetime_value
        description: "Total revenue from customer"
      - name: total_orders
        description: "Number of orders placed"
      - name: value_segment
        description: "Customer value segment (VIP, High Value, Medium Value, etc.)"
      - name: frequency_segment
        description: "Order frequency segment (Frequent, Regular, Occasional, etc.)"
      - name: customer_tier
        description: "Combined RFM tier (Champion, Loyal, At Risk VIP, etc.)"
      - name: activity_status
        description: "Current activity status (Active, At Risk, Dormant, Churned)"

  - name: fct_product_sales
    description: "Product sales fact table with inventory and performance metrics"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Product name"
      - name: category_name
        description: "Product category"
      - name: total_revenue
        description: "Total revenue generated by product"
      - name: total_units_sold
        description: "Total quantity sold"
      - name: performance_tier
        description: "Sales performance tier (Star Product, High Performer, etc.)"
      - name: inventory_action
        description: "Recommended inventory action (Restock, Reduce, Normal, etc.)"
      - name: units_per_month
        description: "Average units sold per month"
